In [6]:
# work space on tensorflow or pytorch

In [7]:
import tensorflow as tf
import torch 
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [8]:
hello =tf.constant("hello,world")

In [9]:
with tf.Session() as sess:
    print(sess.run(hello))

b'hello,world'


In [10]:
x = torch.empty(5,3)
print(x) # 输出 5×3 的未初始化的矩阵, 矩阵元素未初始化, 所以可能是浮点类型的任何职

x = torch.rand(5,3)

x = torch.zeros(5,4,dtype=torch.long)

x = torch.tensor([5.5, 3]) # 直接用常数来初始化一个Tensor

x.size() # Tensor的size


tensor([[ 0.0000e+00,  0.0000e+00,  1.0201e-42],
        [ 0.0000e+00,  7.0065e-45,  0.0000e+00],
        [-4.1800e-17,  4.7224e-43,  0.0000e+00],
        [ 0.0000e+00,  7.0065e-45,  0.0000e+00],
        [-4.1805e-17,  4.7224e-43,  0.0000e+00]])


torch.Size([2])

In [11]:
### 对比numpy 和 torch


In [14]:
np_data=np.arange(6).reshape((2,3))

In [15]:
torch_data=torch.from_numpy(np_data)
print(np_data)
print(torch_data)

[[0 1 2]
 [3 4 5]]
tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32)


In [16]:
np_data = np.arange(6).reshape((2, 3))
torch_data = torch.from_numpy(np_data)
tensor2array = torch_data.numpy()
print(
    '\nnumpy array:', np_data,          # [[0 1 2], [3 4 5]]
    '\ntorch tensor:', torch_data,      #  0  1  2 \n 3  4  5    [torch.LongTensor of size 2x3]
    '\ntensor to array:', tensor2array, # [[0 1 2], [3 4 5]]
)


numpy array: [[0 1 2]
 [3 4 5]] 
torch tensor: tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32) 
tensor to array: [[0 1 2]
 [3 4 5]]


In [17]:
data = [[1,2], [3,4]]
tensor = torch.FloatTensor(data)  # 32-bit floating point
# correct method
print(
    '\nmatrix multiplication (matmul)',
    '\nnumpy: ', np.matmul(data, data),     # [[7, 10], [15, 22]]
    '\ntorch: ', torch.mm(tensor, tensor)   # [[7, 10], [15, 22]]
)


matrix multiplication (matmul) 
numpy:  [[ 7 10]
 [15 22]] 
torch:  tensor([[ 7., 10.],
        [15., 22.]])


In [22]:
from torch.autograd import Variable
tensor=torch.FloatTensor(data)
variable=Variable(tensor,requires_grad=True)

In [23]:
print(tensor)
print(variable)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
